oauth2:
  user:
    google:
      client-id: 339816202566-7pofqikd406mbhn1sldehccnm4m9iofo.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:8080/redirect/oauth
    naver:
      client-id: sMYMSBgFGw1j6Sq0L9Zo
      client-secret: kYrX2V4S7i
      redirect-uri: http://localhost:8080/redirect/oauth
  provider:
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    naver:
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me