spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 339816202566-7pofqikd406mbhn1sldehccnm4m9iofo.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          # 네이버는 spring security가 기본적을 제공해주지 않기 때문에 github, google과 달리 많은 정보를 적어줘야한다.
          naver: 
            client-id: sMYMSBgFGw1j6Sq0L9Zo
            client-secret: kYrX2V4S7i
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response